from builder.pipeline.models import ExchangeResearch
from builder.pipeline.schema_walk import walk_schema

def generate_rust_codegen_prompt() -> str:
    schema = walk_schema(ExchangeResearch)

    return "\n".join([
        "You are a senior Rust engineer working on NautilusTrader.",
        "",
        "TASK:",
        "Generate a COMPLETE Rust adapter core for {EXCHANGE_NAME} from the schema.",
        "",
        "STRICT RULES:",
        "- Follow NautilusTrader adapter standard",
        "- Use smart placeholders (e.g., {{EXCHANGE_NAME}}, {{EXCHANGE_UPPER}}, {{EXCHANGE_LOWER}}, {{REST_URL_MAINNET}}, {{REST_URL_TESTNET}}, {{WS_URL_PUBLIC}}) in your generation where applicable, or replace them if they are in provided snippets",
        "- Async Rust (tokio)",
        "- NO direct `reqwest` usage (strictly forbidden)",
        "- HTTP: `hyper 1.2`, `hyper-util 0.1`, `hyper-rustls 0.26`",
        "- Middleware: `tower 0.4`, Rate Limiting: `governor 0.6` (custom impl)",
        "- Async Runtime: `tokio 1.36`, Serialization: `serde`, `serde_json`",
        "- 100% Rust Core compatible with `Maturin` for Python bindings",
        "- No TODOs",
        "- No placeholders",
        "- No inferred behavior",
        "- DO NOT use `reqwest` (it is not a dependency).",
        "- USE `Hyper 1.2` directly for HTTP requests.",
        "- USE `hyper_util::client::legacy::Client` for common HTTP logic.",
        "- USE `http_body_util::BodyExt` to collect response bytes.",
        "- USE `http::StatusCode` (from `http` crate) for status checks.",
        "- Example error check: `if status.as_u16() >= 400 { ... }`",
        "- DO NOT use `nautilus_core` (it is not a dependency). Use `nautilus_common` or `nautilus_model`.",
        "- Common imports: `nautilus_model::identifiers::AccountId`, `nautilus_common::live::get_runtime`.",
        "",
        "HTTP CLIENT PATTERN (Hyper 1.2):",
        "```rust",
        "use hyper_util::client::legacy::Client;",
        "use hyper_util::client::legacy::connect::HttpConnector;",
        "use hyper_rustls::HttpsConnector;",
        "use http_body_util::BodyExt; // for collect().await?",
        "use http_body_util::Full;",
        "use bytes::Bytes;",
        "",
        "pub struct HttpClient {",
        "    client: Client<HttpsConnector<HttpConnector>, Full<Bytes>>,",
        "}",
        "",
        "// Sending request:",
        "let req = http::Request::builder().method(\"POST\").uri(url).body(Full::new(Bytes::from(body)))?;",
        "let res = self.client.request(req).await?;",
        "let status = res.status();",
        "let body_bytes = res.collect().await?.to_bytes();",
        "```",
        "",
        "OUTPUT FORMAT:",
        "{ \"rust_files\": { \"<relative/path.rs>\": \"<contents>\" } }",
        "",
        "REQUIRED MODULES:",
        "- lib.rs (with module declarations)",
        "- common/consts.rs",
        "- common/urls.rs",
        "- config.rs",
        "- error.rs",
        "- http/client.rs",
        "- http/signing.rs",
        "- websocket/client.rs",
        "- parsing/models.rs",
        "- python/mod.rs (PyO3)",
        "- python/urls.rs",
        "",
        "SCHEMA:",
        *schema,
        "",
        "RESEARCH DATA (JSON):",
        "{SPEC_JSON}",
        "",
        "IMPORTANT:",
        "- Auth and order logic must be exact",
        "- Use `{EXCHANGE_NAME}_API_KEY` and `{EXCHANGE_NAME}_API_SECRET` for environment variables in `credential.rs`",
        "- UNKNOWN means unsupported",
    ])
